

HCOLUMNS_NAMES = {
    # 'baseMonetaria_billetesPublico_total_stock_ars': 'Billetes en poder del público',
    # 'baseMonetaria_billetesEntidades_total_stock_ars': 'Billetes en entidades',
    # 'baseMonetaria_cheques_total_stock_ars': 'Cheques',
    # 'baseMonetaria_ctaCorrienteBCRA_total_stock_ars': 'Cuenta corriente del BCRA',
    # 'baseMonetaria_totalSinCuasi_total_stock_ars': 'Base Monetaria sin Cuasimonedas',
    # 'baseMonetaria_cuasimonedas_total_stock_ars': 'Cuasimonedas',
    # 'baseMonetaria_total_total_stock_ars': 'Base Monetaria',
    # 'reservas_total_total_stock_usd': 'reservas total total stock usd',
    # 'reservas_oroDivisas_total_stock_usd': 'reservas oro divisas total stock usd',
    # 'reservas_pasePasivoExterior_total_stock_usd': 'reservas pase pasivo exterior total stock usd',
    # 'reservas_deg_total_stock_usd': 'reservas deg total stock usd',
    # 'depositos_ctaCorriente_total_stock_ars': 'depositos cta corriente total stock ars',
    # 'depositos_cajaAhorro_total_stock_ars': 'depositos caja ahorro total stock ars',
    # 'depositos_PFTradicional_total_stock_ars': 'depositos PF tradicional total stock ars',
    # 'depositos_PFUVA_total_stock_ars': 'depositos PF UVA total stock ars',
    # 'depositos_otrosDepositos_total_stock_ars': 'depositos otros depositos total stock ars',
    # 'depositos_cedros_total_stock_ars': 'depositos cedros total stock ars',
    # 'depositos_depSinBoden_total_stock_ars': 'depositos dep sin boden total stock ars',
    # 'depositos_boden_total_stock_ars': 'depositos boden total stock ars',
    # 'depositos_depositos_total_stock_ars': 'depositos depositos total stock ars',
    # 'depositos_ctaCorriente_priv_stock_ars': 'depositos cta corriente priv stock ars',
    # 'depositos_cajaAhorro_priv_stock_ars': 'depositos caja ahorro priv stock ars',
    # 'depositos_PFTradicional_priv_stock_ars': 'depositos PF tradicional priv stock ars',
    # 'depositos_PFUVA_priv_stock_ars': 'depositos PF UVA priv stock ars',
    # 'depositos_otrosDepositos_priv_stock_ars': 'depositos otros depositos priv stock ars',
    # 'depositos_cedros_priv_stock_ars': 'depositos cedros priv stock ars',
    # 'depositos_depSinBoden_priv_stock_ars': 'depositos dep sin boden priv stock ars',
    # 'depositos_boden_priv_stock_ars': 'depositos boden priv stock ars',
    # 'depositos_depositos_priv_stock_ars': 'depositos depositos priv stock ars',
    # 'depositos_depositos_total_stock_usd': 'depositos depositos total stock usd',
    # 'depositos_depositos_priv_stock_usd': 'depositos depositos priv stock usd',
    # 'depositos_m2_total_stock_ars': 'depositos m2 total stock ars',
    # 'prestamos_adelantos_priv_stock_ars': 'prestamos adelantos priv stock ars',
    # 'prestamos_documentos_priv_stock_ars': 'prestamos documentos priv stock ars',
    # 'prestamos_hipotecarios_priv_stock_ars': 'prestamos hipotecarios priv stock ars',
    # 'prestamos_prendarios_priv_stock_ars': 'prestamos prendarios priv stock ars',
    # 'prestamos_personales_priv_stock_ars': 'prestamos personales priv stock ars',
    # 'prestamos_tarjetas_priv_stock_ars': 'prestamos tarjetas priv stock ars',
    # 'prestamos_otrosPrestamos_priv_stock_ars': 'prestamos otros prestamos priv stock ars',
    # 'prestamos_total_priv_stock_ars': 'prestamos total priv stock ars',
    # 'prestamos_adelantos_priv_stock_usd': 'prestamos adelantos priv stock usd',
    # 'prestamos_documentos_priv_stock_usd': 'prestamos documentos priv stock usd',
    # 'prestamos_hipotecarios_priv_stock_usd': 'prestamos hipotecarios priv stock usd',
    # 'prestamos_prendarios_priv_stock_usd': 'prestamos prendarios priv stock usd',
    # 'prestamos_personales_priv_stock_usd': 'prestamos personales priv stock usd',
    # 'prestamos_tarjetas_priv_stock_usd': 'prestamos tarjetas priv stock usd',
    # 'prestamos_otrosPrestamos_priv_stock_usd': 'prestamos otros prestamos priv stock usd',
    # 'prestamos_total_priv_stock_usd': 'prestamos total priv stock usd',
    # 'instrumentosBCRA_pasesPasivos_total_stock_ars': 'instrumentos BCRA pases pasivos total stock ars',
    # 'instrumentosBCRA_pasesPasivosFCI_total_stock_ars': 'instrumentos BCRA pases pasivos FCI total stock ars',
    # 'instrumentosBCRA_pasesActivos_total_stock_ars': 'instrumentos BCRA pases activos total stock ars',
    # 'instrumentosBCRA_leliq_total_stock_ars': 'instrumentos BCRA leliq total stock ars',
    # 'instrumentosBCRA_lebac_total_stock_ars': 'instrumentos BCRA lebac total stock ars',
    # 'instrumentosBCRA_lebacEntidades_total_stock_ars': 'instrumentos BCRA lebac entidades total stock ars',
    # 'instrumentosBCRA_lebacUsdLediv_total_stock_usd': 'instrumentos BCRA lebac USD lediv total stock usd',
    # 'instrumentosBCRA_nocom_total_stock_ars': 'instrumentos BCRA nocom total stock ars'
}

