FULL_COLUMNS_NAMES = {
    'baseMonetaria_billetesPublico_total_stock_ars': 'Billetes en poder del público', 
    'baseMonetaria_billetesEntidades_total_stock_ars': 'Billetes en poder de entidades', 
    'baseMonetaria_cheques_total_stock_ars': 'Cheques', 
    'baseMonetaria_ctaCorrienteBCRA_total_stock_ars': 'Cuenta Corriente del BCRA', 
    'baseMonetaria_totalSinCuasi_total_stock_ars': 'Base Monetaria (Sin cuasimonedas)', 
    'baseMonetaria_cuasimonedas_total_stock_ars': 'Cuasimonedas', 
    'baseMonetaria_total_total_stock_ars': 'Base Monetaria', 
    'reservas_total_total_stock_usd': 'Reservas Internacionales (USD)', 
    'reservas_oroDivisas_total_stock_usd': 'Oro/Divisas (USD)', 
    'reservas_pasePasivoExterior_total_stock_usd': 'Pase Pasivo al exterior (USD)', 
    'reservas_deg_total_stock_usd': 'DEG (USD)', 
    'reservas_tipoDeCambio_total_indice_ars': 'Tipo de Cambio (USDARS)', 
    'depositos_ctaCorriente_total_stock_ars': 'Cuentas Corriente (Total)', 
    'depositos_cajaAhorro_total_stock_ars': 'Cajas de Ahorro (Total)', 
    'depositos_PFTradicional_total_stock_ars': 'Plazos Fijo Tradicional (Total)', 
    'depositos_PFUVA_total_stock_ars': 'Plazos Fijo UVA (Total)', 
    'depositos_otrosDepositos_total_stock_ars': 'Otros depósitos (Total)', 
    'depositos_cedros_total_stock_ars': 'Cedros (Total)', 
    'depositos_depSinBoden_total_stock_ars': 'Depósitos sin Boden (Total)', 
    'depositos_boden_total_stock_ars': 'Depósitos Boden (Total)',
    'depositos_depositos_total_stock_ars': 'Depósitos (Total)', 
    'depositos_ctaCorriente_priv_stock_ars': 'Cuentas Corriente (Privados)', 
    'depositos_cajaAhorro_priv_stock_ars': 'Cajas de Ahorro (Privados)', 
    'depositos_PFTradicional_priv_stock_ars': 'Plazos Fijo Tradicional (Privados)', 
    'depositos_PFUVA_priv_stock_ars': 'Plazos Fijo UVA (Privados)',
    'depositos_otrosDepositos_priv_stock_ars': 'Otros depósitos (Privados)', 
    'depositos_cedros_priv_stock_ars': 'Cedros (Privados)', 
    'depositos_depSinBoden_priv_stock_ars': 'Depósitos sin Boden (Privados)', 
    'depositos_boden_priv_stock_ars': 'Depósitos Boden (Privados)', 
    'depositos_depositos_priv_stock_ars': 'Depósitos (Privados)', 
    'depositos_depositos_total_stock_usd': 'Depósitos en USD (Total)', 
    'depositos_depositos_priv_stock_usd': 'Depósitos en USD (Privados)', 
    'depositos_m2_total_stock_ars': 'M2', 
    'prestamos_adelantos_priv_stock_ars': 'Adelantos (Privados)', 
    'prestamos_documentos_priv_stock_ars': 'Documentos (Privados)', 
    'prestamos_hipotecarios_priv_stock_ars': 'Prést. Hipotecarios (Privados)', 
    'prestamos_prendarios_priv_stock_ars': 'Prendarios (Privados)', 
    'prestamos_personales_priv_stock_ars': 'Prést. Personales (Privados)', 
    'prestamos_tarjetas_priv_stock_ars': 'Tarjetas de Crédito (Privados)', 
    'prestamos_otrosPrestamos_priv_stock_ars': 'Otros préstamos (Privados)', 
    'prestamos_total_priv_stock_ars': 'Total de préstamos (Privados)', 
    'prestamos_adelantos_priv_stock_usd': 'Adelantos en USD (Privados)', 
    'prestamos_documentos_priv_stock_usd': 'Documentos en USD (Privados)', 
    'prestamos_hipotecarios_priv_stock_usd': 'Prést. Hipotecarios en USD (Privados)', 
    'prestamos_prendarios_priv_stock_usd': 'Prendarios en USD (Privados)', 
    'prestamos_personales_priv_stock_usd': 'Prést. Personales en USD (Privados)', 
    'prestamos_tarjetas_priv_stock_usd': 'Tarjetas de Crédito en USD (Privados)', 
    'prestamos_otrosPrestamos_priv_stock_usd': 'Otros préstamos en USD (Privados)', 
    'prestamos_total_priv_stock_usd': 'Total de préstamos en USD (Privados)', 
    'instrumentosBCRA_pasesPasivos_total_stock_ars': 'Pases Pasivos', 
    'instrumentosBCRA_pasesPasivosFCI_total_stock_ars': 'Pases Pasivos de FCI', 
    'instrumentosBCRA_pasesActivos_total_stock_ars': 'Pases Activos', 
    'instrumentosBCRA_leliq_total_stock_ars': 'LeLiqs', 
    'instrumentosBCRA_lebac_total_stock_ars': 'Lebacs', 
    'instrumentosBCRA_lebacEntidades_total_stock_ars': 'Lebacs de Entidades', 
    'instrumentosBCRA_lebacUsdLediv_total_stock_usd': 'Lebac USD / LeDiv', 
    'instrumentosBCRA_nocom_total_stock_ars': 'Nocoms', 
    'indices_CER_total_indice_ars': 'Índice CER', 
    'agregadosMonetarios_CirculacionMonetaria_total_stock_ars': 'Circulación Monetaria', 
    'agregadosMonetarios_ledivUSDexpEnARS_total_stock_ars': 'LeDiv (en ARS)', 
    'agregadosMonetarios_pasivosRemuneradores_total_stock_ars': 'Pasivos Remunerados del BCRA', 
    'agregadosMonetarios_baseMonetariaAmpliada_total_stock_ars': 'Base Monetaria Ampliada', 
    'agregadosMonetarios_baseMonetariaVSPasivosRemunerados_total_indice_ars': 'Base Monetaria / Pasivos Remuneradores', 
    'agregadosMonetarios_m3_total_stock_ars': 'M3'
}

